# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/facialgui.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1409, 790)
        MainWindow.setMinimumSize(QtCore.QSize(1409, 790))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("font: 13pt \"Verdana\";\n"
"background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(50, 70))
        self.pushButton.setStyleSheet("border-image:url(/Users/humairaahmed/Downloads/capitalone);")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setMinimumSize(QtCore.QSize(1160, 0))
        self.label.setStyleSheet("text-align: center;\n"
"font: 18pt \".SF NS Text\";\n"
"font-weight: bold; \n"
"color: rgb(219, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.browseButton = QtWidgets.QPushButton(self.frame)
        self.browseButton.setStyleSheet("QPushButton{\n"
"background:  #014971;\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px 18px;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(0, 96, 173);\n"
"}")
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.filepath = QtWidgets.QLineEdit(self.frame)
        self.filepath.setMinimumSize(QtCore.QSize(1100, 0))
        self.filepath.setCursor(QtGui.QCursor(QtCore.Qt.BlankCursor))
        self.filepath.setObjectName("filepath")
        self.horizontalLayout.addWidget(self.filepath)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.processButton = QtWidgets.QPushButton(self.frame)
        self.processButton.setStyleSheet("QPushButton{\n"
"background:  #014971;\n"
"color: rgb(255, 255, 255);\n"
"padding: 10px 18px;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(0, 96, 173);\n"
"}")
        self.processButton.setObjectName("processButton")
        self.horizontalLayout.addWidget(self.processButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.uploaded = QtWidgets.QLabel(self.frame)
        self.uploaded.setMaximumSize(QtCore.QSize(16777215, 300))
        self.uploaded.setStyleSheet("color: rgb(219, 0, 0);")
        self.uploaded.setObjectName("uploaded")
        self.gridLayout.addWidget(self.uploaded, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.analysed = QtWidgets.QLabel(self.frame)
        self.analysed.setMaximumSize(QtCore.QSize(16777215, 300))
        self.analysed.setStyleSheet("color: rgb(219, 0, 0);")
        self.analysed.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.analysed.setObjectName("analysed")
        self.gridLayout.addWidget(self.analysed, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setStyleSheet("QLabel{ color: #014971;\n"
"}\n"
"\n"
"QScrollBar{\n"
"background: #014971;\n"
"width: 10px; \n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("")
        self.page_1.setObjectName("page_1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.listWidget_1 = QtWidgets.QListWidget(self.page_1)
        self.listWidget_1.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_1.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_1.setObjectName("listWidget_1")
        self.gridLayout_12.addWidget(self.listWidget_1, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.page_1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_12.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_1)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.page_1)
        self.label_1.setStyleSheet("")
        self.label_1.setObjectName("label_1")
        self.gridLayout_12.addWidget(self.label_1, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.page_1)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_12.addWidget(self.label_5, 0, 4, 1, 1)
        self.listWidget_2 = QtWidgets.QListWidget(self.page_1)
        self.listWidget_2.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_2.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_2.setObjectName("listWidget_2")
        self.gridLayout_12.addWidget(self.listWidget_2, 1, 1, 1, 1)
        self.listWidget_3 = QtWidgets.QListWidget(self.page_1)
        self.listWidget_3.setStyleSheet("")
        self.listWidget_3.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_3.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_3.setObjectName("listWidget_3")
        self.gridLayout_12.addWidget(self.listWidget_3, 1, 2, 1, 1)
        self.listWidget_4 = QtWidgets.QListWidget(self.page_1)
        self.listWidget_4.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_4.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_4.setObjectName("listWidget_4")
        self.gridLayout_12.addWidget(self.listWidget_4, 1, 3, 1, 1)
        self.listWidget_5 = QtWidgets.QListWidget(self.page_1)
        self.listWidget_5.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_5.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_5.setObjectName("listWidget_5")
        self.gridLayout_12.addWidget(self.listWidget_5, 1, 4, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_12)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 4, 1, 1)
        self.listWidget_6 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_6.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_6.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_6.setObjectName("listWidget_6")
        self.gridLayout_3.addWidget(self.listWidget_6, 1, 0, 1, 1)
        self.listWidget_7 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_7.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_7.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_7.setObjectName("listWidget_7")
        self.gridLayout_3.addWidget(self.listWidget_7, 1, 1, 1, 1)
        self.listWidget_8 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_8.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_8.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_8.setObjectName("listWidget_8")
        self.gridLayout_3.addWidget(self.listWidget_8, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.listWidget_9 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_9.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_9.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_9.setObjectName("listWidget_9")
        self.gridLayout_3.addWidget(self.listWidget_9, 1, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setStyleSheet("")
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 3, 1, 1)
        self.listWidget_10 = QtWidgets.QListWidget(self.page_2)
        self.listWidget_10.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_10.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_10.setObjectName("listWidget_10")
        self.gridLayout_3.addWidget(self.listWidget_10, 1, 4, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.page_3)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.page_3)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.page_3)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 4, 1, 1)
        self.listWidget_11 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_11.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_11.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_11.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_11.setObjectName("listWidget_11")
        self.gridLayout_4.addWidget(self.listWidget_11, 1, 0, 1, 1)
        self.listWidget_12 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_12.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_12.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_12.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_12.setObjectName("listWidget_12")
        self.gridLayout_4.addWidget(self.listWidget_12, 1, 1, 1, 1)
        self.listWidget_13 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_13.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_13.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_13.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_13.setObjectName("listWidget_13")
        self.gridLayout_4.addWidget(self.listWidget_13, 1, 2, 1, 1)
        self.listWidget_14 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_14.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_14.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_14.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_14.setObjectName("listWidget_14")
        self.gridLayout_4.addWidget(self.listWidget_14, 1, 3, 1, 1)
        self.listWidget_15 = QtWidgets.QListWidget(self.page_3)
        self.listWidget_15.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_15.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_15.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_15.setObjectName("listWidget_15")
        self.gridLayout_4.addWidget(self.listWidget_15, 1, 4, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_4)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_19 = QtWidgets.QLabel(self.page_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.page_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_4)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.page_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.page_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 0, 4, 1, 1)
        self.listWidget_16 = QtWidgets.QListWidget(self.page_4)
        self.listWidget_16.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_16.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_16.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_16.setObjectName("listWidget_16")
        self.gridLayout_5.addWidget(self.listWidget_16, 1, 0, 1, 1)
        self.listWidget_17 = QtWidgets.QListWidget(self.page_4)
        self.listWidget_17.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_17.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_17.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_17.setObjectName("listWidget_17")
        self.gridLayout_5.addWidget(self.listWidget_17, 1, 1, 1, 1)
        self.listWidget_18 = QtWidgets.QListWidget(self.page_4)
        self.listWidget_18.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_18.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_18.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_18.setObjectName("listWidget_18")
        self.gridLayout_5.addWidget(self.listWidget_18, 1, 2, 1, 1)
        self.listWidget_19 = QtWidgets.QListWidget(self.page_4)
        self.listWidget_19.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_19.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_19.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_19.setObjectName("listWidget_19")
        self.gridLayout_5.addWidget(self.listWidget_19, 1, 3, 1, 1)
        self.listWidget_20 = QtWidgets.QListWidget(self.page_4)
        self.listWidget_20.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget_20.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_20.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_20.setObjectName("listWidget_20")
        self.gridLayout_5.addWidget(self.listWidget_20, 1, 4, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_22 = QtWidgets.QLabel(self.page_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 1, 1, 1)
        self.listWidget_25 = QtWidgets.QListWidget(self.page_5)
        self.listWidget_25.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_25.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_25.setObjectName("listWidget_25")
        self.gridLayout_6.addWidget(self.listWidget_25, 1, 4, 1, 1)
        self.listWidget_24 = QtWidgets.QListWidget(self.page_5)
        self.listWidget_24.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_24.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_24.setObjectName("listWidget_24")
        self.gridLayout_6.addWidget(self.listWidget_24, 1, 3, 1, 1)
        self.listWidget_21 = QtWidgets.QListWidget(self.page_5)
        self.listWidget_21.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_21.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_21.setObjectName("listWidget_21")
        self.gridLayout_6.addWidget(self.listWidget_21, 1, 0, 1, 1)
        self.listWidget_23 = QtWidgets.QListWidget(self.page_5)
        self.listWidget_23.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_23.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_23.setObjectName("listWidget_23")
        self.gridLayout_6.addWidget(self.listWidget_23, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.page_5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 1)
        self.listWidget_22 = QtWidgets.QListWidget(self.page_5)
        self.listWidget_22.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_22.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_22.setObjectName("listWidget_22")
        self.gridLayout_6.addWidget(self.listWidget_22, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 0, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page_5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 0, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_29 = QtWidgets.QLabel(self.page_6)
        self.label_29.setObjectName("label_29")
        self.gridLayout_8.addWidget(self.label_29, 0, 3, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.page_6)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.page_6)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.page_6)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 2, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.page_6)
        self.label_30.setObjectName("label_30")
        self.gridLayout_8.addWidget(self.label_30, 0, 4, 1, 1)
        self.listWidget_26 = QtWidgets.QListWidget(self.page_6)
        self.listWidget_26.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_26.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_26.setObjectName("listWidget_26")
        self.gridLayout_8.addWidget(self.listWidget_26, 1, 0, 1, 1)
        self.listWidget_27 = QtWidgets.QListWidget(self.page_6)
        self.listWidget_27.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_27.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_27.setObjectName("listWidget_27")
        self.gridLayout_8.addWidget(self.listWidget_27, 1, 1, 1, 1)
        self.listWidget_28 = QtWidgets.QListWidget(self.page_6)
        self.listWidget_28.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_28.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_28.setObjectName("listWidget_28")
        self.gridLayout_8.addWidget(self.listWidget_28, 1, 2, 1, 1)
        self.listWidget_29 = QtWidgets.QListWidget(self.page_6)
        self.listWidget_29.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_29.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_29.setObjectName("listWidget_29")
        self.gridLayout_8.addWidget(self.listWidget_29, 1, 3, 1, 1)
        self.listWidget_30 = QtWidgets.QListWidget(self.page_6)
        self.listWidget_30.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_30.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_30.setObjectName("listWidget_30")
        self.gridLayout_8.addWidget(self.listWidget_30, 1, 4, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_8)
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_34 = QtWidgets.QLabel(self.page_7)
        self.label_34.setObjectName("label_34")
        self.gridLayout_9.addWidget(self.label_34, 0, 3, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.page_7)
        self.label_32.setObjectName("label_32")
        self.gridLayout_9.addWidget(self.label_32, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.page_7)
        self.label_31.setObjectName("label_31")
        self.gridLayout_9.addWidget(self.label_31, 0, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.page_7)
        self.label_33.setObjectName("label_33")
        self.gridLayout_9.addWidget(self.label_33, 0, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.page_7)
        self.label_35.setObjectName("label_35")
        self.gridLayout_9.addWidget(self.label_35, 0, 4, 1, 1)
        self.listWidget_31 = QtWidgets.QListWidget(self.page_7)
        self.listWidget_31.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_31.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_31.setObjectName("listWidget_31")
        self.gridLayout_9.addWidget(self.listWidget_31, 1, 0, 1, 1)
        self.listWidget_32 = QtWidgets.QListWidget(self.page_7)
        self.listWidget_32.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_32.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_32.setObjectName("listWidget_32")
        self.gridLayout_9.addWidget(self.listWidget_32, 1, 1, 1, 1)
        self.listWidget_33 = QtWidgets.QListWidget(self.page_7)
        self.listWidget_33.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_33.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_33.setObjectName("listWidget_33")
        self.gridLayout_9.addWidget(self.listWidget_33, 1, 2, 1, 1)
        self.listWidget_34 = QtWidgets.QListWidget(self.page_7)
        self.listWidget_34.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_34.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_34.setObjectName("listWidget_34")
        self.gridLayout_9.addWidget(self.listWidget_34, 1, 3, 1, 1)
        self.listWidget_35 = QtWidgets.QListWidget(self.page_7)
        self.listWidget_35.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_35.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_35.setObjectName("listWidget_35")
        self.gridLayout_9.addWidget(self.listWidget_35, 1, 4, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_9)
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_39 = QtWidgets.QLabel(self.page_8)
        self.label_39.setObjectName("label_39")
        self.gridLayout_10.addWidget(self.label_39, 0, 3, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.page_8)
        self.label_37.setObjectName("label_37")
        self.gridLayout_10.addWidget(self.label_37, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.page_8)
        self.label_36.setObjectName("label_36")
        self.gridLayout_10.addWidget(self.label_36, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.page_8)
        self.label_38.setObjectName("label_38")
        self.gridLayout_10.addWidget(self.label_38, 0, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.page_8)
        self.label_40.setObjectName("label_40")
        self.gridLayout_10.addWidget(self.label_40, 0, 4, 1, 1)
        self.listWidget_36 = QtWidgets.QListWidget(self.page_8)
        self.listWidget_36.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_36.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_36.setObjectName("listWidget_36")
        self.gridLayout_10.addWidget(self.listWidget_36, 1, 0, 1, 1)
        self.listWidget_37 = QtWidgets.QListWidget(self.page_8)
        self.listWidget_37.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_37.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_37.setObjectName("listWidget_37")
        self.gridLayout_10.addWidget(self.listWidget_37, 1, 1, 1, 1)
        self.listWidget_38 = QtWidgets.QListWidget(self.page_8)
        self.listWidget_38.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_38.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_38.setObjectName("listWidget_38")
        self.gridLayout_10.addWidget(self.listWidget_38, 1, 2, 1, 1)
        self.listWidget_39 = QtWidgets.QListWidget(self.page_8)
        self.listWidget_39.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_39.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_39.setObjectName("listWidget_39")
        self.gridLayout_10.addWidget(self.listWidget_39, 1, 3, 1, 1)
        self.listWidget_40 = QtWidgets.QListWidget(self.page_8)
        self.listWidget_40.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_40.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_40.setObjectName("listWidget_40")
        self.gridLayout_10.addWidget(self.listWidget_40, 1, 4, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_10)
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page_9)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_44 = QtWidgets.QLabel(self.page_9)
        self.label_44.setObjectName("label_44")
        self.gridLayout_11.addWidget(self.label_44, 0, 3, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.page_9)
        self.label_42.setObjectName("label_42")
        self.gridLayout_11.addWidget(self.label_42, 0, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.page_9)
        self.label_41.setObjectName("label_41")
        self.gridLayout_11.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.page_9)
        self.label_43.setObjectName("label_43")
        self.gridLayout_11.addWidget(self.label_43, 0, 2, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.page_9)
        self.label_45.setObjectName("label_45")
        self.gridLayout_11.addWidget(self.label_45, 0, 4, 1, 1)
        self.listWidget_41 = QtWidgets.QListWidget(self.page_9)
        self.listWidget_41.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_41.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_41.setObjectName("listWidget_41")
        self.gridLayout_11.addWidget(self.listWidget_41, 1, 0, 1, 1)
        self.listWidget_42 = QtWidgets.QListWidget(self.page_9)
        self.listWidget_42.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_42.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_42.setObjectName("listWidget_42")
        self.gridLayout_11.addWidget(self.listWidget_42, 1, 1, 1, 1)
        self.listWidget_43 = QtWidgets.QListWidget(self.page_9)
        self.listWidget_43.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_43.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_43.setObjectName("listWidget_43")
        self.gridLayout_11.addWidget(self.listWidget_43, 1, 2, 1, 1)
        self.listWidget_44 = QtWidgets.QListWidget(self.page_9)
        self.listWidget_44.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_44.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_44.setObjectName("listWidget_44")
        self.gridLayout_11.addWidget(self.listWidget_44, 1, 3, 1, 1)
        self.listWidget_45 = QtWidgets.QListWidget(self.page_9)
        self.listWidget_45.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_45.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_45.setObjectName("listWidget_45")
        self.gridLayout_11.addWidget(self.listWidget_45, 1, 4, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_11)
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_49 = QtWidgets.QLabel(self.page_10)
        self.label_49.setObjectName("label_49")
        self.gridLayout_7.addWidget(self.label_49, 0, 3, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.page_10)
        self.label_47.setObjectName("label_47")
        self.gridLayout_7.addWidget(self.label_47, 0, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.page_10)
        self.label_46.setObjectName("label_46")
        self.gridLayout_7.addWidget(self.label_46, 0, 0, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.page_10)
        self.label_48.setObjectName("label_48")
        self.gridLayout_7.addWidget(self.label_48, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.page_10)
        self.label_50.setObjectName("label_50")
        self.gridLayout_7.addWidget(self.label_50, 0, 4, 1, 1)
        self.listWidget_46 = QtWidgets.QListWidget(self.page_10)
        self.listWidget_46.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_46.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_46.setObjectName("listWidget_46")
        self.gridLayout_7.addWidget(self.listWidget_46, 1, 0, 1, 1)
        self.listWidget_47 = QtWidgets.QListWidget(self.page_10)
        self.listWidget_47.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_47.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_47.setObjectName("listWidget_47")
        self.gridLayout_7.addWidget(self.listWidget_47, 1, 1, 1, 1)
        self.listWidget_48 = QtWidgets.QListWidget(self.page_10)
        self.listWidget_48.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_48.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_48.setObjectName("listWidget_48")
        self.gridLayout_7.addWidget(self.listWidget_48, 1, 2, 1, 1)
        self.listWidget_49 = QtWidgets.QListWidget(self.page_10)
        self.listWidget_49.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_49.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_49.setObjectName("listWidget_49")
        self.gridLayout_7.addWidget(self.listWidget_49, 1, 3, 1, 1)
        self.listWidget_50 = QtWidgets.QListWidget(self.page_10)
        self.listWidget_50.setIconSize(QtCore.QSize(150, 150))
        self.listWidget_50.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget_50.setObjectName("listWidget_50")
        self.gridLayout_7.addWidget(self.listWidget_50, 1, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_7)
        self.stackedWidget.addWidget(self.page_10)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.backButton = QtWidgets.QPushButton(self.frame)
        self.backButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.backButton.setStyleSheet("QPushButton{\n"
"background: #014971;\n"
"color: rgb(255, 255, 255);\n"
"padding: 5px 10px;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(0, 96, 173);\n"
"}")
        self.backButton.setObjectName("backButton")
        self.horizontalLayout_13.addWidget(self.backButton)
        self.pageNumber = QtWidgets.QLabel(self.frame)
        self.pageNumber.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pageNumber.setStyleSheet("text-align: center;\n"
"font: 16pt \".SF NS Text\";\n"
"color: rgb(219, 0, 0);")
        self.pageNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.pageNumber.setObjectName("pageNumber")
        self.horizontalLayout_13.addWidget(self.pageNumber)
        self.forwardButton = QtWidgets.QPushButton(self.frame)
        self.forwardButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.forwardButton.setStyleSheet("QPushButton{\n"
"background: #014971;\n"
"color: rgb(255, 255, 255);\n"
"padding: 5px 10px;\n"
"border-radius: 8px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background: rgb(0, 96, 173);\n"
"}")
        self.forwardButton.setObjectName("forwardButton")
        self.horizontalLayout_13.addWidget(self.forwardButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "                                                                                            Facial Recognition "))
        self.browseButton.setText(_translate("MainWindow", "Browse"))
        self.processButton.setText(_translate("MainWindow", "Process"))
        self.uploaded.setText(_translate("MainWindow", "Uploaded Image"))
        self.analysed.setText(_translate("MainWindow", "Analysed Image"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_1.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_16.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.label_25.setText(_translate("MainWindow", "TextLabel"))
        self.label_29.setText(_translate("MainWindow", "TextLabel"))
        self.label_27.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.label_30.setText(_translate("MainWindow", "TextLabel"))
        self.label_34.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "TextLabel"))
        self.label_31.setText(_translate("MainWindow", "TextLabel"))
        self.label_33.setText(_translate("MainWindow", "TextLabel"))
        self.label_35.setText(_translate("MainWindow", "TextLabel"))
        self.label_39.setText(_translate("MainWindow", "TextLabel"))
        self.label_37.setText(_translate("MainWindow", "TextLabel"))
        self.label_36.setText(_translate("MainWindow", "TextLabel"))
        self.label_38.setText(_translate("MainWindow", "TextLabel"))
        self.label_40.setText(_translate("MainWindow", "TextLabel"))
        self.label_44.setText(_translate("MainWindow", "TextLabel"))
        self.label_42.setText(_translate("MainWindow", "TextLabel"))
        self.label_41.setText(_translate("MainWindow", "TextLabel"))
        self.label_43.setText(_translate("MainWindow", "TextLabel"))
        self.label_45.setText(_translate("MainWindow", "TextLabel"))
        self.label_49.setText(_translate("MainWindow", "TextLabel"))
        self.label_47.setText(_translate("MainWindow", "TextLabel"))
        self.label_46.setText(_translate("MainWindow", "TextLabel"))
        self.label_48.setText(_translate("MainWindow", "TextLabel"))
        self.label_50.setText(_translate("MainWindow", "TextLabel"))
        self.backButton.setText(_translate("MainWindow", "<"))
        self.pageNumber.setText(_translate("MainWindow", "Page 1"))
        self.forwardButton.setText(_translate("MainWindow", ">"))


